/*Select all records from Players_Played table*/
SELECT ...
FROM PlayersPlayed_Final
;
/*SELECT Match_ID and Player_ID records from the Players_Played table for Players playing for England. */
SELECT ...
FROM PlayersPlayed_Final WHERE team_initials = '...'
;
/*SELECT all records from the MATCHES table for matches in the Final but not 2002. */
SELECT *
FROM ...
WHERE stage = 'Final' and Year ...
;
/*SELECT Player_ID and Player_Name from the Players table for all Players with RAY in their name.*/
SELECT ... ,...
FROM Players_Final
WHERE player_name like '...'
;
/*COUNT the number of Matches in the Matches table.*/
SELECT COUNT(...) Number_of_Matches FROM Matches_Final
;
/*COUNT the number of players in Players table, by Team Initials.*/
SELECT team_initials, ,...
FROM Players_Final GROUP BY ...
;
/*SUM the number of home and away team goals for each Year from the Matches table. Which has more each year?*/
SELECT ...
,sum(home_team_goals) as Home_Team_Goals ,sum(...)
FROM Matches_Final GROUP BY ...
;
/*Show the AVERAGE number of goals scored by each player in the Players_Played table, only for players who HAVE an average above 0.7.*/
SELECT ... ,avg(...)
FROM PlayersPlayed_Final GROUP BY player_id HAVING ...
;
/*Join Matches and Players_Played and SELECT the Year, Player_ID and number of goals for players who have played AND scored in a World Cup Final.*/
SELECT ... ,... ,...
FROM Matches_Final AS m
INNER JOIN PlayersPlayed_Final AS pp
ON m. = pp.
WHERE stage = ... AND number_of_goals ...
;
/*SELECT PLAYER_NAME, TEAM_INITIALS, YEAR and SUM of goals, for players who HAVE scored 4 or more goals at a single World Cup*/
SELECT ... ,... ,... ,...
FROM Matches_Final m
INNER JOIN PlayersPlayed_Final pp
ON m. = pp. INNER JOIN Players_Final plyrs
ON plyrs. = pp. GROUP BY ...
,... HAVING ...
,...
;