/*How many goals were scored at each World Cup?*/
/*Hint : Number_of_Goals in Players_Played and Year in Matches*/

select ...
	  ,...
from PlayersPlayed_Final pp
Inner join Matches_Final m 
	on ...
group by ...
;

/*Who was the Referee for the 2006 final?*/
/*(Hint : Referee in Officials, Stage and Year in Matches)*/

Select ...
from ... as M
Inner JOIN ... as o 
	on m.matchid = o.matchid
where ... = ... and stage = ...
;

/* What are the names and ID's of the Stadiums that have held over 6 matches? How many have they held?*/
/*(Hint : Stadium details in Stadiums and Match numbers in Matches)*/

Select s.stadium_id
	  ,s.stadium
      ,...(m.matchid) as Number_of_Matches
from ... as m
Inner JOIN ... as s 
	on ... = ...
group by ...
		,...
having ...
;

/*Can you find the Host Country and non-Final stages of World Cup’s that had an average attendance above 60,000?*/
/*(Hint : Attendance in Match_Attendances, Country in Host_Countries)*/

Select ...
	  ,...
      ,...
from ...
Inner join Attendances_Final as a
	on ... = ...
Inner Join Hosts_Final as h
	on ... = ...
where ...
group by ...
	    ,...
Having ...
;
/*How many players have played over 5 matches at stages with “final” in the name? What country are they all from?*/
/*(Hint :Stage in matches, player information in Players_Played and Players. Watch out for different case letters)*/

select ...
	  ,...
      ,...
from Matches_Final m
Inner join ...
	on ... = ...
Inner join ...
	on ... = ...
where stage like '...' 
group by ...
		,...
...
;